var classes = [
    {
        "name": "Roulette\\Game",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cycle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Roulette\\Wheel",
            "Roulette\\Table",
            "Roulette\\Player"
        ],
        "parents": [],
        "lcom": 1,
        "length": 27,
        "vocabulary": 8,
        "volume": 81,
        "difficulty": 3.67,
        "effort": 297,
        "level": 0.27,
        "bugs": 0.03,
        "time": 17,
        "intelligentContent": 22.09,
        "number_operators": 5,
        "number_operands": 22,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 22,
        "loc": 49,
        "lloc": 27,
        "mi": 97.95,
        "mIwoC": 54.88,
        "commentWeight": 43.07,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.14,
        "relativeSystemComplexity": 100.14,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0.27,
        "totalSystemComplexity": 200.27,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Roulette\\Table",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placeBet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cleanBets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBets",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Roulette\\Wheel",
            "Roulette\\Bet",
            "Roulette\\Bet",
            "Roulette\\InvalidBetException",
            "Roulette\\Bet"
        ],
        "parents": [],
        "lcom": 1,
        "length": 46,
        "vocabulary": 16,
        "volume": 184,
        "difficulty": 9.9,
        "effort": 1821.6,
        "level": 0.1,
        "bugs": 0.06,
        "time": 101,
        "intelligentContent": 18.59,
        "number_operators": 13,
        "number_operands": 33,
        "number_operators_unique": 6,
        "number_operands_unique": 10,
        "cloc": 46,
        "loc": 87,
        "lloc": 41,
        "mi": 93.7,
        "mIwoC": 48.56,
        "commentWeight": 45.15,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.77,
        "relativeSystemComplexity": 16.77,
        "totalStructuralComplexity": 96,
        "totalDataComplexity": 4.6,
        "totalSystemComplexity": 100.6,
        "pageRank": 0.02,
        "afferentCoupling": 7,
        "efferentCoupling": 3,
        "instability": 0.3,
        "violations": {}
    },
    {
        "name": "Roulette\\IntegerStatistics",
        "interface": false,
        "methods": [
            {
                "name": "addDuration",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addMaxima",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mean",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "standardDeviation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "results",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 90,
        "vocabulary": 30,
        "volume": 441.62,
        "difficulty": 14.14,
        "effort": 6245.77,
        "level": 0.07,
        "bugs": 0.15,
        "time": 347,
        "intelligentContent": 31.23,
        "number_operators": 24,
        "number_operands": 66,
        "number_operators_unique": 9,
        "number_operands_unique": 21,
        "cloc": 46,
        "loc": 87,
        "lloc": 41,
        "mi": 91.17,
        "mIwoC": 46.03,
        "commentWeight": 45.15,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.27,
        "relativeSystemComplexity": 5.27,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 6.33,
        "totalSystemComplexity": 26.33,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Roulette\\PlayerCancellation",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPlaying",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetSequence",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restartPlayer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placeBets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "win",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player",
            "Roulette\\Table",
            "parent",
            "Roulette\\Bet",
            "Roulette\\Bet",
            "parent",
            "Roulette\\Bet",
            "parent"
        ],
        "parents": [
            "Roulette\\Player"
        ],
        "lcom": 1,
        "length": 65,
        "vocabulary": 20,
        "volume": 280.93,
        "difficulty": 10.07,
        "effort": 2829.32,
        "level": 0.1,
        "bugs": 0.09,
        "time": 157,
        "intelligentContent": 27.89,
        "number_operators": 18,
        "number_operands": 47,
        "number_operators_unique": 6,
        "number_operands_unique": 14,
        "cloc": 51,
        "loc": 99,
        "lloc": 48,
        "mi": 90.87,
        "mIwoC": 46.05,
        "commentWeight": 44.83,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.24,
        "relativeSystemComplexity": 25.24,
        "totalStructuralComplexity": 175,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 176.67,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Roulette\\SevenRedsPlayer",
        "interface": false,
        "methods": [
            {
                "name": "placeBets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "winners",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Roulette\\MartingalePlayer",
            "parent",
            "Roulette\\Bin",
            "Roulette\\Outcome"
        ],
        "parents": [
            "Roulette\\MartingalePlayer"
        ],
        "lcom": 1,
        "length": 22,
        "vocabulary": 11,
        "volume": 76.11,
        "difficulty": 4.29,
        "effort": 326.17,
        "level": 0.23,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 17.76,
        "number_operators": 7,
        "number_operands": 15,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 21,
        "loc": 42,
        "lloc": 21,
        "mi": 102.04,
        "mIwoC": 57.58,
        "commentWeight": 44.46,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 4.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 8.33,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Roulette\\Player",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placeBets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restartPlayer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "winners",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "win",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPlaying",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setAmount",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAmount",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRoundsToGo",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setStake",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStake",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRoundsPlayed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Table",
            "Roulette\\Bin",
            "Roulette\\Bet",
            "Roulette\\Bet"
        ],
        "parents": [],
        "lcom": 4,
        "length": 63,
        "vocabulary": 19,
        "volume": 267.62,
        "difficulty": 11.96,
        "effort": 3200.28,
        "level": 0.08,
        "bugs": 0.09,
        "time": 178,
        "intelligentContent": 22.38,
        "number_operators": 22,
        "number_operands": 41,
        "number_operators_unique": 7,
        "number_operands_unique": 12,
        "cloc": 89,
        "loc": 147,
        "lloc": 58,
        "mi": 91.1,
        "mIwoC": 44.4,
        "commentWeight": 46.7,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.54,
        "relativeSystemComplexity": 5.54,
        "totalStructuralComplexity": 52,
        "totalDataComplexity": 20,
        "totalSystemComplexity": 72,
        "pageRank": 0.02,
        "afferentCoupling": 8,
        "efferentCoupling": 3,
        "instability": 0.27,
        "violations": {}
    },
    {
        "name": "Roulette\\Outcome",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "winAmount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "equals",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHash",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Outcome"
        ],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 13,
        "volume": 107.31,
        "difficulty": 4.44,
        "effort": 476.95,
        "level": 0.23,
        "bugs": 0.04,
        "time": 26,
        "intelligentContent": 24.15,
        "number_operators": 9,
        "number_operands": 20,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 42,
        "loc": 73,
        "lloc": 31,
        "mi": 99.25,
        "mIwoC": 53.11,
        "commentWeight": 46.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.83,
        "relativeSystemComplexity": 3.83,
        "totalStructuralComplexity": 6,
        "totalDataComplexity": 17,
        "totalSystemComplexity": 23,
        "pageRank": 0.73,
        "afferentCoupling": 9,
        "efferentCoupling": 2,
        "instability": 0.18,
        "violations": {}
    },
    {
        "name": "Roulette\\Player1326State",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "currentBet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nextWon",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nextLost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player1326",
            "Roulette\\Player1326StateFactory",
            "Roulette\\Bet"
        ],
        "parents": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 6,
        "volume": 46.53,
        "difficulty": 6,
        "effort": 279.18,
        "level": 0.17,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 7.75,
        "number_operators": 6,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 44,
        "loc": 69,
        "lloc": 25,
        "mi": 104.94,
        "mIwoC": 57.69,
        "commentWeight": 47.24,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.08,
        "relativeSystemComplexity": 5.08,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 4.33,
        "totalSystemComplexity": 20.33,
        "pageRank": 0.02,
        "afferentCoupling": 4,
        "efferentCoupling": 3,
        "instability": 0.43,
        "violations": {}
    },
    {
        "name": "Roulette\\RandomPlayer",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placeBets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "selectRandomOutcome",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restartPlayer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Roulette\\Player",
            "Roulette\\Table",
            "parent",
            "Clickalicious\\Rng\\Generator",
            "Roulette\\Bet"
        ],
        "parents": [
            "Roulette\\Player"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 12,
        "volume": 107.55,
        "difficulty": 4,
        "effort": 430.2,
        "level": 0.25,
        "bugs": 0.04,
        "time": 24,
        "intelligentContent": 26.89,
        "number_operators": 6,
        "number_operands": 24,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 20,
        "loc": 50,
        "lloc": 30,
        "mi": 94.67,
        "mIwoC": 53.15,
        "commentWeight": 41.52,
        "kanDefect": 0.61,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.16,
        "relativeSystemComplexity": 49.16,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 0.63,
        "totalSystemComplexity": 196.63,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Roulette\\Passenger57",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placeBets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restartPlayer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player",
            "Roulette\\Table",
            "parent",
            "Roulette\\Bet"
        ],
        "parents": [
            "Roulette\\Player"
        ],
        "lcom": 2,
        "length": 14,
        "vocabulary": 6,
        "volume": 36.19,
        "difficulty": 1.2,
        "effort": 43.43,
        "level": 0.83,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 30.16,
        "number_operators": 2,
        "number_operands": 12,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 22,
        "loc": 41,
        "lloc": 19,
        "mi": 106.38,
        "mIwoC": 61.06,
        "commentWeight": 45.32,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.07,
        "relativeSystemComplexity": 16.07,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 0.2,
        "totalSystemComplexity": 48.2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Roulette\\Player1326NoWins",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player1326State",
            "Roulette\\Player1326",
            "parent"
        ],
        "parents": [
            "Roulette\\Player1326State"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0.75,
        "effort": 13.93,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 24.77,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 13,
        "lloc": 10,
        "mi": 103.04,
        "mIwoC": 69.17,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Roulette\\Bin",
        "interface": false,
        "methods": [
            {
                "name": "hasOutcome",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllOutcomes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Equip\\Structure\\Set",
            "Roulette\\Outcome"
        ],
        "parents": [
            "Equip\\Structure\\Set"
        ],
        "lcom": 2,
        "length": 10,
        "vocabulary": 5,
        "volume": 23.22,
        "difficulty": 2,
        "effort": 46.44,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 11.61,
        "number_operators": 4,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 19,
        "loc": 36,
        "lloc": 17,
        "mi": 108.32,
        "mIwoC": 63.19,
        "commentWeight": 45.12,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 10.33,
        "pageRank": 0.02,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "Roulette\\Player1326",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placebets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restartPlayer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "win",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player",
            "Roulette\\Table",
            "parent",
            "Roulette\\Player1326NoWins",
            "Roulette\\Bet",
            "parent",
            "Roulette\\Bet",
            "parent"
        ],
        "parents": [
            "Roulette\\Player"
        ],
        "lcom": 2,
        "length": 23,
        "vocabulary": 6,
        "volume": 59.45,
        "difficulty": 1.9,
        "effort": 112.96,
        "level": 0.53,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 31.29,
        "number_operators": 4,
        "number_operands": 19,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 36,
        "loc": 66,
        "lloc": 30,
        "mi": 100.74,
        "mIwoC": 55.22,
        "commentWeight": 45.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 49.08,
        "totalStructuralComplexity": 245,
        "totalDataComplexity": 0.38,
        "totalSystemComplexity": 245.38,
        "pageRank": 0.02,
        "afferentCoupling": 5,
        "efferentCoupling": 5,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Roulette\\FibonacciPlayer",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restartCounters",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "increaseCounters",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placeBets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "win",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restartPlayer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player",
            "Roulette\\Table",
            "parent",
            "Roulette\\Outcome",
            "Roulette\\Bet",
            "Roulette\\Bet",
            "parent",
            "Roulette\\Bet",
            "parent"
        ],
        "parents": [
            "Roulette\\Player"
        ],
        "lcom": 1,
        "length": 39,
        "vocabulary": 10,
        "volume": 129.56,
        "difficulty": 3.88,
        "effort": 502.03,
        "level": 0.26,
        "bugs": 0.04,
        "time": 28,
        "intelligentContent": 33.43,
        "number_operators": 8,
        "number_operands": 31,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 42,
        "loc": 85,
        "lloc": 43,
        "mi": 93.75,
        "mIwoC": 49.44,
        "commentWeight": 44.31,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.07,
        "relativeSystemComplexity": 25.07,
        "totalStructuralComplexity": 175,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 175.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Roulette\\BinBuilder",
        "interface": false,
        "methods": [
            {
                "name": "buildBins",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateStraightBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateSplitBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createLeftRightSplits",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createUpDownSplits",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateStreetBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateCornerBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateLineBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateDozenBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateColumnBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateEvenMoneyBets",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isLow",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEven",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isRed",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateFiveBet",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 14,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 15,
        "ccnMethodMax": 5,
        "externals": [
            "Roulette\\Wheel",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome",
            "Roulette\\Outcome"
        ],
        "parents": [],
        "lcom": 1,
        "length": 538,
        "vocabulary": 102,
        "volume": 3589.76,
        "difficulty": 22.45,
        "effort": 80574.61,
        "level": 0.04,
        "bugs": 1.2,
        "time": 4476,
        "intelligentContent": 159.93,
        "number_operators": 125,
        "number_operands": 413,
        "number_operators_unique": 10,
        "number_operands_unique": 92,
        "cloc": 61,
        "loc": 239,
        "lloc": 178,
        "mi": 59.26,
        "mIwoC": 24,
        "commentWeight": 35.26,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 225.28,
        "totalStructuralComplexity": 3375,
        "totalDataComplexity": 4.13,
        "totalSystemComplexity": 3379.13,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Roulette\\MartingalePlayer",
        "interface": false,
        "methods": [
            {
                "name": "win",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lose",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placeBets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restartPlayer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player",
            "Roulette\\Bet",
            "parent",
            "Roulette\\Bet",
            "parent",
            "Roulette\\Outcome",
            "Roulette\\Bet"
        ],
        "parents": [
            "Roulette\\Player"
        ],
        "lcom": 1,
        "length": 45,
        "vocabulary": 11,
        "volume": 155.67,
        "difficulty": 6.19,
        "effort": 963.24,
        "level": 0.16,
        "bugs": 0.05,
        "time": 54,
        "intelligentContent": 25.16,
        "number_operators": 12,
        "number_operands": 33,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 32,
        "loc": 63,
        "lloc": 31,
        "mi": 96.64,
        "mIwoC": 51.98,
        "commentWeight": 44.65,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 9.13,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 36.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "Roulette\\Bet",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "winAmount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loseAmount",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAmount",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "representation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOutcome",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Outcome"
        ],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 10,
        "volume": 96.34,
        "difficulty": 2.63,
        "effort": 252.88,
        "level": 0.38,
        "bugs": 0.03,
        "time": 14,
        "intelligentContent": 36.7,
        "number_operators": 8,
        "number_operands": 21,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 45,
        "loc": 80,
        "lloc": 35,
        "mi": 98.17,
        "mIwoC": 52.29,
        "commentWeight": 45.88,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.1,
        "relativeSystemComplexity": 6.1,
        "totalStructuralComplexity": 28,
        "totalDataComplexity": 14.67,
        "totalSystemComplexity": 42.67,
        "pageRank": 0.05,
        "afferentCoupling": 9,
        "efferentCoupling": 1,
        "instability": 0.1,
        "violations": {}
    },
    {
        "name": "Roulette\\Wheel",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addOutcome",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "next",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOutcome",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllBins",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateRandomNumber",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 6,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Roulette\\Bin",
            "Roulette\\BinBuilder",
            "Clickalicious\\Rng\\Generator",
            "Roulette\\Outcome"
        ],
        "parents": [],
        "lcom": 1,
        "length": 61,
        "vocabulary": 20,
        "volume": 263.64,
        "difficulty": 13.33,
        "effort": 3515.17,
        "level": 0.08,
        "bugs": 0.09,
        "time": 195,
        "intelligentContent": 19.77,
        "number_operators": 21,
        "number_operands": 40,
        "number_operators_unique": 8,
        "number_operands_unique": 12,
        "cloc": 52,
        "loc": 104,
        "lloc": 52,
        "mi": 89.53,
        "mIwoC": 45.08,
        "commentWeight": 44.46,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.22,
        "relativeSystemComplexity": 37.22,
        "totalStructuralComplexity": 252,
        "totalDataComplexity": 8.57,
        "totalSystemComplexity": 260.57,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Roulette\\InvalidBetException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 7,
        "lloc": 4,
        "mi": 213.45,
        "mIwoC": 171,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Roulette\\Player1326TwoWins",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player1326State",
            "Roulette\\Player1326",
            "parent"
        ],
        "parents": [
            "Roulette\\Player1326State"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0.75,
        "effort": 13.93,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 24.77,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 13,
        "lloc": 10,
        "mi": 103.04,
        "mIwoC": 69.17,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Roulette\\Player1326OneWin",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player1326State",
            "Roulette\\Player1326",
            "parent"
        ],
        "parents": [
            "Roulette\\Player1326State"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0.75,
        "effort": 13.93,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 24.77,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 13,
        "lloc": 10,
        "mi": 103.04,
        "mIwoC": 69.17,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Roulette\\Player1326StateFactory",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "name"
        ],
        "parents": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 6,
        "effort": 248.16,
        "level": 0.17,
        "bugs": 0.01,
        "time": 14,
        "intelligentContent": 6.89,
        "number_operators": 4,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 25,
        "loc": 42,
        "lloc": 17,
        "mi": 108.09,
        "mIwoC": 61.57,
        "commentWeight": 46.51,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Roulette\\Simulator",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "session",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "gather",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Roulette\\Game",
            "Roulette\\Player",
            "Roulette\\IntegerStatistics"
        ],
        "parents": [],
        "lcom": 1,
        "length": 47,
        "vocabulary": 15,
        "volume": 183.62,
        "difficulty": 8.75,
        "effort": 1606.71,
        "level": 0.11,
        "bugs": 0.06,
        "time": 89,
        "intelligentContent": 20.99,
        "number_operators": 12,
        "number_operands": 35,
        "number_operators_unique": 5,
        "number_operands_unique": 10,
        "cloc": 52,
        "loc": 90,
        "lloc": 38,
        "mi": 95.47,
        "mIwoC": 49.28,
        "commentWeight": 46.18,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 81.17,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 243.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Roulette\\Player1326ThreeWins",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Roulette\\Player1326State",
            "Roulette\\Player1326",
            "parent"
        ],
        "parents": [
            "Roulette\\Player1326State"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0.75,
        "effort": 13.93,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 24.77,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 13,
        "lloc": 10,
        "mi": 103.04,
        "mIwoC": 69.17,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    }
]